#!/usr/bin/env bash

# Open file in a running neovim instance with neomim-remote
#   - Dependencies: neovim, neovim-remote

SERVICE='nvim'
 
if pgrep -f "$SERVICE" > /dev/null; then
    nvr "$1"
else
    "${EDITOR:-nvim}" "$1"
fi
