#!/usr/bin/env sh

# Open file in a running neovim instance with neomim-remote
#   - Dependencies: neovim, neovim-remote
# Shell: POSIX compliant

SERVICE='nvim'
 
if pgrep -f "$SERVICE" >/dev/null; then
  nvr "$1"
else
  if command -v nv >/dev/null 2>&1; then 
    nv "$1"
  else
    "${EDITOR:-nvim}" "$1"
  fi
fi
