#!/usr/bin/env sh

# Open file in a new window with neovim
#   - Dependencies: neovim
# Shell: POSIX compliant

if command -v nv >/dev/null 2>&1; then
  alacritty -e nv "$nnn"
else
  alacritty -e "${EDITOR:-nvim}" "$nnn"
fi
