#!/usr/bin/env sh

# Fuzzy find a file in directory subtree with fzf and edit in neovim
# Open in a running instance with neovim-remote if possible

SERVICE='nvim'
 
if pgrep -f "$SERVICE" > /dev/null; then
    nvr "$(fd -t f | fzf)"
else
    if [ -x "$HOME"/bin/nv ]; then
        nv "$(fd -t f | fzf)"
    else
        nvim "$(fd -t f | fzf)"
    fi
fi
