#!/usr/bin/env sh

# Description: Fuzzy find a file in directory subtree with fzf and open using xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

# Check if a fd is in the user's PATH
if command -v fd >/dev/null 2>&1; then
    cmd="$FZF_DEFAULT_COMMAND"
    [ -z "$cmd" ] && cmd="fd . -t f 2>/dev/null"
    entry="$(eval "$cmd" | fzf --delimiter / --nth=-1 --tiebreak=begin --info=hidden)"
else
    cmd="$FZF_DEFAULT_COMMAND"
    [ -z "$cmd" ] && cmd="find . -type f 2>/dev/null"
    entry="$(eval "$cmd" | fzf --delimiter / --nth=-1 --tiebreak=begin --info=hidden)"
fi

case "$(file -biL "$entry")" in
    *text*)
        "${VISUAL:-$EDITOR}" "$entry" ;;
    *)
        xdg-open "$entry" >/dev/null 2>&1 ;;
esac

