#!/usr/bin/env sh

# Description: Fuzzy find a file in directory subtree with fzf and open using xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana
if [ -x /usr/bin/fd ]; then
    xdg-open "$(fd -t f | fzf)" >/dev/null 2>&1
else
    xdg-open "$(find -type f | fzf)" >/dev/null 2>&1
fi

