#!/usr/bin/env bash

# Description: Set the selected image as wallpaper using nitrogen. Just put the cursor on a image and run the script.
#
# Shell: POSIX Compliant
# Author: juacq97

if ! [ -z "$1" ]; then
    nitrogen --set-zoom-fill --save $1
    notify-send -a "nnn" "Wallpaper changed!"
fi
