#!/usr/bin/env bash
# ( https://github.com/f0x52/dots/blob/master/bin/bin/select_st )
read -r X Y W H < <(slop -f "%x %y %w %h" -b 1 -t 0 -q)
# Width and Height in px need to be converted to columns/rows
# To get these magic values, make a fullscreen st, and divide your screen width by ${tput cols}, height by ${tput lines} 
(( W /= 8 ))
(( H /= 16 ))
x=${W}x${H}
y=+${X}+${Y}
bspc rule -a Alacritty -o state=floating
alacritty --position $x $y
