#!/usr/bin/env sh
# Open file in a running neovim instance with neomim-remote
# ( https://github.com/mhinz/neovim-remote )

SERVICE='nvim'
 
if pgrep -f "$SERVICE" > /dev/null; then
    nvr "$1"
else
    if [ -x "$HOME"/.bin/nv ]; then
        nv "$1"
    else
        nvim "$1"
    fi
fi
