#!/usr/bin/env sh

# Fuzzy find a file in directory subtree with fzf and edit in neovim
# Open in a running instance with neovim-remote if possible

SERVICE='nvim'
 
if ps ax | grep -v grep | grep $SERVICE > /dev/null;then
    nvr "$(fd -t f | fzf)"
else
    nvim "$(fd -t f | fzf)"
fi
