#!/usr/bin/env sh

# Description: Fuzzy find a file in directory subtree with fzf and open using xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

xdg-open "$(fd --type f | fzf)" >/dev/null 2>&1
