#! /bin/sh
# $HOME/.conifg/bspwm/bspwmrc

# Autostart
# Start sxhkd in azerty
sxhkd -m1 &
# Start Polybar
$HOME/.config/polybar/launch.sh
# Change X shaped default cursor
 xsetroot -cursor_name left_ptr
# Start dunst
dunst &

# SETTINGS
bspc config border_width        3
bspc config window_gap          8
bspc config top_padding         22
bspc config bottom_padding      0
bspc config right_padding       30
bspc config left_padding        30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config presel_feedback      true

bspc config focus_follows_pointer true
bspc config pointer_modifier      shift
bspc config pointer_follows_focus true

# THEME
bspc config focused_border_color \#2dcbb0
bspc config normal_border_color \#534666
bspc config presel_feedback_color \#3e3350

bspc monitor -d I II III IV V VI VII VIII IX X

# PROGRAMS RULES
# Get name with 'xprop | grep WM_CLASS'
bspc rule -a Vivaldi-stable border=off
bspc rule -a Firefox border=off
bspc rule -a Lxappearance state=floating center=true
bspc rule -a qBittorrent desktop='^7' state=floating center=true rectangle=1376x625+0+0
bspc rule -a mpv state=floating center=true
bspc rule -a Molotov state=floating center=true
bspc rule -a Xarchiver state=floating center=true
bspc rule -a Gimp follow=on state=floating center=true
