#!/bin/sh
# Like normal cd but opens an interactive navigation window when called with no arguments
#   - Dependencies: fzf

fcd () {
    local lsd
    local dir

    if [[ "$#" != 0 ]]; then
        builtin cd "$@" || exit;
        return
    fi

    while true; do
        lsd=$(echo ".." && ls -p | grep '/$' | sed 's;/$;;')
        dir="$(printf '%s\n' "${lsd[@]}" |
            fzf --reverse --preview '
                    __cd_nxt="$(echo {})";
                    __cd_path="$(echo $(pwd)/${__cd_nxt} | sed "s;//;/;")";
                    echo $__cd_path;
                    echo;
                    ls -p --color=always "${__cd_path}";
                    ')"
                    [[ ${#dir} != 0 ]] || return 0
                    builtin cd "$dir" &> /dev/null || exit
    done
}
