#!/bin/sh
# fuzzy grep via rg and open in vim with line number
#   - Dependencies: fzf, rg, neovim

frg () {
    local file
    local line

    read -r file line <<<"$(rg --no-heading --line-number 2> /dev/null "$@" | fzf -0 -1 | awk -F: '{print $1, $2}')"

    # Open with neovim development prerelease build if exist
    if [ -x "$HOME"/bin/nv ]; then
        [[ -n "$file" ]] && nv "$file" +"$line"
    else
        [[ -n "$file" ]] && ${EDITOR:-nvim} "$file" +"$line"
    fi
}
